### ISSUE TITLE
Support EmitDefaultValues

### ISSUE THREAD

**Issue by awltr** [mfridman/protoc-gen-go-json#5]
Currently the option `emit_defaults` maps to `EmitUnpopulated`. But there is a new option `EmitDefaultValues`, see [protojson#MarshalOptions](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions)

Any chance to add this? I would suggest option `emit_defaults_without_null` or similar

**Comment by mfridman** [comment]
Sure, I'll add it tonight and cut a release.

**Comment by mfridman** [comment]
Alright, I added the `emit_defaults_without_null` and it's mapped to [`EmitDefaultValues`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions).

I also cut a [`v1.4.0` release](https://github.com/mfridman/protoc-gen-go-json/releases/tag/v1.4.0)
